### ISSUE TITLE
Front Camera

### ISSUE THREAD

**Issue by brainstormapps** [duddns/Andorid-OpenCV-Portrait-Camera#1]
Hi I used your portrait camera code, it run perfectly for back camera, but for front camera when i used
        mOpenCvCameraView.setCameraIndex(1);
the out is down to up.
How can use your code perfectly for front camera.

**Comment by huanjulu** [comment]
one queesion is that 
how can get full screen ?

**Comment by agustindev** [comment]
I have the solution to fullscreen mode 💃 and working with front camera

**Comment by agustindev** [comment]
this repo project is great to contrib opencv project

**Comment by duddns** [comment]
@brainstormapps 
I am sorry too late response.
Added camera change code.

**Comment by duddns** [comment]
@huanjulu 
I am sorry too late response.
try change this file

app/src/main/res/layout/activity_main.xml
```
<kr.dont.portrait_camera.lib.PortraitCameraView
        android:id="@+id/cameraView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        opencv:show_fps="true"
        opencv:camera_id="back" />
```

**Comment by duddns** [comment]
@agustindev 
Thanks for the comment.

**Comment by duddns** [comment]
Close issue
