### ISSUE TITLE
PortraitCameraView Display in FullScreen

### ISSUE THREAD

**Issue by Jethvasagar** [duddns/Andorid-OpenCV-Portrait-Camera#3]
`PortraitCameraView`   It leaves some residual space above and below the preview. How to display CameraView FullScreen.

`   <com.opencvcamerapreview.opencv.PortraitCameraView
        android:layout_height="match_parent"
        android:layout_width="match_parent"
        opencv:camera_id="any"
        opencv:show_fps="false"
        android:id="@+id/tutorial1_activity_java_surface_view"
        android:visibility="gone"/>`

java Code

`mOpenCvCameraView = (PortraitCameraBridgeViewBase) findViewById(R.id.tutorial1_activity_java_surface_view);
        mOpenCvCameraView.setVisibility(SurfaceView.VISIBLE);
        mOpenCvCameraView.setCvCameraViewListener(this);
        mOpenCvCameraView.setMaxFrameSize(640, 840);
`

**Comment by duddns** [comment]
@Jethvasagar 

I am sorry too late response.
Take a look at this part.

[PortraitCameraBridgeViewBase.java](https://github.com/duddns/Andorid-OpenCV-Portrait-Camera/blob/master/app/src/main/java/kr/dont/portrait_camera/lib/PortraitCameraBridgeViewBase.java)

    protected Size calculateCameraFrameSize(List<?> supportedSizes, ListItemAccessor accessor, int surfaceWidth, int surfaceHeight) {
        int calcWidth = 0;
        int calcHeight = 0;

        int maxAllowedWidth = (mMaxWidth != MAX_UNSPECIFIED && mMaxWidth < surfaceWidth)? mMaxWidth : surfaceWidth;
        int maxAllowedHeight = (mMaxHeight != MAX_UNSPECIFIED && mMaxHeight < surfaceHeight)? mMaxHeight : surfaceHeight;

        for (Object size : supportedSizes) {
            int width = accessor.getWidth(size);
            int height = accessor.getHeight(size);

            if (width <= maxAllowedWidth && height <= maxAllowedHeight) {
                if (width >= calcWidth && height >= calcHeight) {
                    calcWidth = (int) width;
                    calcHeight = (int) height;
                }
            }
        }

        return new Size(calcWidth, calcHeight);
    }
